### PR TITLE
Add support for a rootPath for all apps

### PR DESCRIPTION
**Pull request by wokalski**
Thanks for making the project. It seems to perfectly align with our setup @dialohq. I'm now testing nixidy out in a sandbox cluster and needed this little change.

I want all of the apps to be on the same (main) branch. This PR adds an option to nixidy to allow that.

### CODE REVIEW

**Comment by arnarg** [comment]
I'm sorry I never responded to this pull request. Simply adding the rootPath prefix to the application won't do much as the generated resources will not be present under `rootPath` prefix, unless you're manually copying the generated resources in the correct location.

**Comment by wokalski** [comment]
i am copying them there manually.

**Comment by arnarg** [comment]
Ok, in that case if you can fix the conflict I'm willing to merge this.

Looking at the docs for `lib.path.subpath.join`, it seems to also normalize the path and therefor add `./` prefix to the generated string, is this not an issue when parsed by Argo CD in your experience?

**Comment by wokalski** [comment]
It works with my argocd setup :). Will rebase!

**Comment by arnarg** [comment]
I wanted to get this change in ASAP so I made it myself but I set you as co-author: https://github.com/arnarg/nixidy/commit/79bcd51dcc17c15664b9058839d59a3f1054590f

**Comment by wokalski** [comment]
i appecaite it. I haven't done it cause i have some other local changes i still need to commit/upstream.

**Comment by arnarg** [comment]
Thanks for the contribution! The way I was doing things was quite literally from [The Rendered Manifest Pattern](https://akuity.io/blog/the-rendered-manifests-pattern/) post where I would push rendered manifests to orphan branches. I'm assuming you are putting them in a sub-directory on your main branch or something similar?

I switched my personal cluster config to this setup and I think I like it better! https://github.com/arnarg/cluster

I have also created a generator that can take in a CRD and spit out nix resource options compatible with the ones generated in kubenix (I re-used a lot of their code for this).

By defining this: https://github.com/arnarg/cluster/blob/7fa4fddf7c79e726cd462690fd27897219f1454b/flake.nix#L53

I can generate resource options for `CiliumNetworkPolicy` and `CiliumClusterwideNetworkPolicy` so I can define them like this:
https://github.com/arnarg/cluster/blob/7fa4fddf7c79e726cd462690fd27897219f1454b/modules/argocd/default.nix#L62

I hope you can find use for this too and I plan to document this all soon hopefully.

**Comment by wokalski** [comment]
I can't wait for the post on nixos discourse bout this ;)

**Comment by arnarg** [comment]
I have released an initial v0.1.0 and here you go:
https://discourse.nixos.org/t/nixidy-kubernetes-gitops-with-nix-and-argo-cd/48034

😅

**Pull request closed without merging**
